services:
    frontend:
        build: .
        image: shoes-frontend:dev
        environment:
            SERVICE_VERSION: v1
networks:
    default:
        external:
            name: int221-network
